// <auto-generated />
using INTIA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace INTIA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250411155707_SeedCustomers")]
    partial class SeedCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("INTIA.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Alice",
                            Lastname = "Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Bob",
                            Lastname = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Charlie",
                            Lastname = "Brown"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "Diana",
                            Lastname = "Prince"
                        },
                        new
                        {
                            Id = 5,
                            Firstname = "Ethan",
                            Lastname = "Hunt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
